### ISSUE TITLE
Update 1.0.6 breaks with autoloader error

### ISSUE THREAD

**Issue by mnemotiv** [deliciousbrains/wp-migrate-db#95]
Right after upgrade to 1.0.6 - I get this (PHP 7.0.32 on Apache, Plesk 17.5.3 server):

```
Fatal error: Uncaught Error: Call to undefined method Composer\Autoload\ClassLoader::setClassMapAuthoritative() in /var/www/vhosts/anonymous.com/httpdocs/wp-content/plugins/wp-migrate-db/vendor/composer/autoload_real.php:38 Stack trace: #0 /var/www/vhosts/anonymous.com/httpdocs/wp-content/plugins/wp-migrate-db/vendor/autoload.php(7): ComposerAutoloaderInit6f497b9a6dd436300fa985a250762cda::getLoader() #1 /var/www/vhosts/anonymous.com/httpdocs/wp-content/plugins/wp-migrate-db/class/Container.php(13): require('/var/www/vhosts...') #2 /var/www/vhosts/anonymous.com/httpdocs/wp-content/plugins/wp-migrate-db/class/Container.php(20): DeliciousBrains\WPMDB\Container->__construct() #3 /var/www/vhosts/anonymous.com/httpdocs/wp-content/plugins/wp-migrate-db/class/WPMigrateDB.php(33): DeliciousBrains\WPMDB\Container::getInstance() #4 /var/www/vhosts/anonymous.com/httpdocs/wp-content/plugins/wp-migrate-db/setup-mdb.php(14): DeliciousBrains\WPMDB\WPMigrateDB->__construct() #5 /var/www/vhosts/anonymous.com/httpdocs/wp-content/plug in /var/www/vhosts/anonymous.com/httpdocs/wp-content/plugins/wp-migrate-db/vendor/composer/autoload_real.php on line 38
```

**Comment by ptasker** [comment]
Hi there, this is fixed in version 1.0.7.
